export const API_URLS = {
  READ: 'https://integradorwebhook.sanjaworks.com/webhook/dashboard-produtor-leitura-dados',
  CREATE: 'https://integradorwebhook.sanjaworks.com/webhook/dashboard-produtor-criar-dados',
  DELETE: 'https://integradorwebhook.sanjaworks.com/webhook/dashboard-produtor-deletar-dados',
};

export const CATEGORIAS = [
  "DEDUCOES DE VENDA",
  "DESPESAS DE PESSOAL",
  "DESPESAS DE GESTAO",
  "DESPESAS DE MARKETING",
  "DESPESAS OPERACIONAIS GERAIS",
  "DESPESAS DE VENDAS",
  "DESPESAS ADM E FINANCEIRA",
  "DESP INVESTIMENTOS",
  "DESPESAS DIVERSAS (OUTRAS)"
];

export const SUBCATEGORIAS_AMP = [
    "DEDUCOES DE VENDA", "DESP PESS-ALUGUEL", "DESP PESS-EXAMES", "DESP PESS-FÉRIAS", "DESP PESS-FGTS", "DESP PESS-H EXTRA", "DESP PESS-INSS", "DESP PESS-PROVISÃO", "DESP PESS-REFEIÇÃO", "DESP PESS-RESCISÃO", "DESP PESS-RET SOCIOS", "DESP PESS-SALÁRIOS", "DESP PESS-SINDICATO", "DESP PESS-VIAGENS E ESTADIAS", "DESP-GESTAO-ADVOGADOS", "DESP-GESTAO-ALMOXARIFADO", "DESP-GESTAO-AGUA", "DESP-GESTAO-ENERGIA", "DESP-GESTAO-ENTREGAS", "DESP-GESTAO-GAS", "DESP-GESTAO-MANUTENÇÕES", "DESP-GESTAO-MULTAS", "DESP-GESTAO-SOFTWARE", "DESP-GESTAO-SUP PROFISSIONAL", "DESP-GESTAO-PROVISÃO", "DESP-GESTAO-TELEFONIA", "DESP-GESTAO-USO E CONSUMO", "DESPESAS DE MARKETING", "DESP OP GERAIS-ALUGUEL", "DESP OP GERAIS-PROVISÃO", "DESP OP GERAIS-SEGUROS", "DESPESAS DE VENDAS", "DESP ADM FIN-CAPITAL DE GIRO", "DESP ADM FIN-EMPRESTIMO", "DESP ADM FIN-TARIFAS", "DESPESAS ADM E FINANCEIRA", "DESP INVESTIMENTOS"
];

export const SUBCATEGORIAS_ESP = [
    "COFINS", "COFINS-FLV", "CSLL", "CSLL-FLV", "DARF DAS CAB", "DARF DAS LUCIANA", "DARF DAS RENATA", "DARF RENDIMENTO SOCIOS FLV", "DARF RENDIMENTO SOCIOS CAB", "DARF RENDIMENTO SOCIOS LUCIANA", "DARF RENDIMENTO SOCIOS RENATA", "ICMS", "ICMS-ST", "IRRF", "IRPJ", "IRPJ-FLV", "PIS", "PIS-FLV", "ALUGUEL - BEATRIZ RH", "ALUGUEL - ADEMILSON DEPOSITO", "ALUGUEL - ALOJAMENTO", "MEDICINA OCUPACIONAL", "FÉRIAS", "FGTS", "FGTS - RESCISÃO", "FGTS- CAB NUNES", "FGTS FLV", "FGTS- LUCIANA", "FGTS- RENATA", "H EXTRA", "H EXTRA -FERIADO", "H EXTRA - DOMINGO - AÇOUGUE", "H EXTRA - DOMINGO - FRIOS", "H EXTRA - DOMINGO - CAIXAS", "H EXTRA - DOMINGO - DEPOSITO", "H EXTRA - DOMINGO - PADARIA", "H EXTRA - DOMINGO - FISCAL DE CAIXA / SUPERVISÃO", "HORA EXTRA", "HORA-EXTRA", "HORA-EXTRA BALANCO GERAL", "HORA-EXTRA BALANCO PERECIVEL", "INSS", "INSS- CAB NUNES", "INSS- LUCIANA", "INSS- RENATA", "INSS-FLV", "INSS-FLV RURAL", "PROVISÃO DE INSS", "PROVISÃO DE SALÁRIO", "PROVISAO DISSÍDIO", "REFEIÇÃO", "GRATIFICAÇÃO", "CARTAZISTA TERCEIRO", "GRRF", "RECISAO COMPLEMENTAR", "RESCISAO", "RESCISAO - ARAL", "RETIRADA DE SOCIOS", "SALARIO - ARAL", "SALARIO - EXTRA ANDRE", "SALARIO FISCAL DE CAIXA", "SALARIO JOVEM APRENDIZ", "SALARIOS -ACOUGUE", "SALARIOS -ADM", "SALARIOS -CAIXA", "SALARIOS -DEPOSITO", "SALARIOS -FRIOS", "SALARIOS -GERENCIA / LIDERES", "SALARIOS -HORT", "SALARIOS -LIMPEZA", "SALARIOS -PADARIA", "SALARIOS -SEÇÃO", "SALARIOS -TRANSPORTE", "SALARIOS-EMPACOTADOR", "SINDICATO", "VALE TRANSPORTE COLABORADORES - DIFERENÇA", "VIAGENS / ESTADIAS", "CONSULTORIAS -ADVOGADOS ANTERO/AMARAL", "ALMOXARIFADO CARTAZISTA", "AÇOUGUE ALMOXARIFADO", "FRENTE DE CAIXA ALMOXARIFADO", "FRIOS ALMOXARIFADO", "HORT FRUIT ALMOXARIFADO", "LIMPEZA ALMOXARIFADO", "LOJA ALMOXARIFADO", "PADARIA ALMOXARIFADO", "ROTISSERIA ALMOXARIFADO", "UNIFORME ALMOXARIFADO", "AGUA -LOJA", "LUZ -LUZ LOJA", "LUZ -POSTO (DIESEL GERADOR)", "LUZ - SALA RENATA / LUCIANA", "SERVICO TERC", "GAS REFEITORIO", "MANUT EQUIP", "MANUT IMÓVEIS", "MANUT VEICULOS", "MULTAS DIVERSAS", "OLHO NA VALIDADE", "BRINDE", "DOAÇÃO", "LEILÃO", "CONVENIO LOJA (ALOJAMENTO)", "CONVENIO DIRETORIA", "PROVISÃO DE MULTAS LOJA 6 (5.500,00 ANO)", "HONORARIOS LANUNES", "HONORARIOS CAB", "HONORARIOS RENATA", "HONORARIOS LUCIANA", "HONORARIOS MURY FLV", "CONSINCO (RATEIO)", "SUPORTE CONSINCO", "SUPORTE PROF.- CONTABILIDADE MURY", "SUPORTE PROF.- NUTRICIONISTA SILVANA", "SUPORTE PROF.- SEGURANÇA LOJA", "TELEFONE - RENATA", "TELEFONE -TELEFONE", "TELEFONE -TELEFONE VIVO MÓVEL (Rateio)", "INTERNET - LOJA", "INTERNET - FLV", "MAT CONSUMO INTERNO-USO CONSUMO AÇOUGUE", "MAT CONSUMO INTERNO-USO CONSUMO CAFE", "MAT CONSUMO INTERNO-USO CONSUMO COZINHA", "MAT CONSUMO INTERNO-USO CONSUMO FRIOS", "MAT CONSUMO INTERNO-USO CONSUMO LIMPEZA", "MAT CONSUMO INTERNO-USO CONSUMO LOJA", "MAT CONSUMO INTERNO-USO CONSUMO PADARIA", "MAT USO E CONSUMO ADMINISTRAÇAO", "MAT USO E CONSUMO CARTAZISTA", "MAT USO E CONSUMO FRENTE DE CAIXA", "MAT USO E CONSUMO HORT FRUT", "MATERIAL DE CONSTRUÇÃO SANTA LUZIA", "USO E CONSUMO - ROTISSERIA", "USO E CONSUMO CAFÉ CLIENTE", "USO E CONSUMO MANUTENÇÃO", "MENSALIDADE \"ECAD\"", "PROVISÃO COQUETEL", "PUBLICIDADE - ECO PANFLETAGEM (ROSANA)", "PUBLICIDADE -KATU EDIT. GRAFICA", "ALUGUEL -LOJA", "ALUGUEL -SALA RENATA", "ALUGUEL -SALA LUCIANA", "BOLETO SISTEMA FLV OFF JOSÉ RUI", "PROVISÃO ALUGUEL PROPRIO", "PROVISAO IPTU", "PROVISAO IPVA", "PROVISAO SEGURO LOJAS", "ALARME", "DEDETIZAÇÃO", "DIVERSOS", "INADIMPLENCIA (CHEQUES)", "PAPELARIA", "POSTO", "POSTO FROTA EMPRESA (RATEIO)", "SEM PARAR (RATEIO)", "SERASA", "CAPITAL DE GIRO BRADESCO", "BANCO DO BRASIL - EMPRESTIMO", "ENC EXCESSO LIMITE BRADESCO 8%", "ENC LIMITE DE CREDITO BRADESCO 8%", "ENCARGO C GARANTIDA CONTRATO 4070549 SAFRA", "MORA CONTA GARANTIDA SAFRA", "SAFRA", "TARIFA - ITAU ARAL", "TARIFA - ALIMENTAÇÃO CIELO", "TARIFA - ELO DEBITO", "TARIFA - GREENCARD REDECARD", "TARIFA - HIPERCARD CIELO", "TARIFA - REDECARD", "TARIFA - SISCRED", "TARIFA - MURY", "TARIFA DE MANUTENÇÃO CONTA CORRENTE", "TARIFA HIPERCARD REDECARD", "TARIFA SOFTNEX", "TARIFA TED", "TARIFA TRANSFERENCIA DE VALOR", "TARIFA VEGASCARD", "TARIFA VEROCARD", "TARIFAS -AMERICAN EXPRESS", "TARIFAS -CREDSYSTEM", "TARIFAS -DMCARD", "TARIFAS -ELECTRON", "TARIFAS -ELO CARD CREDITO", "TARIFAS -ELO CARD DEBITO", "TARIFAS -GREEN CARD", "TARIFAS -MASTERCARD", "TARIFAS -PLANTAO CARD", "TARIFAS -REDESHOP", "TARIFAS -SODEXO ALIM", "TARIFAS -SODEXO REF", "TARIFAS -TICKET RC", "TARIFAS -V A SMART", "TARIFAS -V R BENEFICIO", "TARIFAS -VALE CARD", "TARIFAS -VISA", "TARIFAS -VISA VALE", "TARIFAS BANCO -BRADESCO / EXCED TRANSF VIA INT", "TARIFAS BANCO -BRADESCO / TRANSF VALORES", "TARIFAS DINNERS", "ALELO ALIMENTAÇÃO CIELO", "INVESTIMENTO"
];

export const RESPONSAVEIS = ["B", "R", "J"];

export const STATUS_OPTIONS = ["mes bloqueado", "liberado para lançamento"];

export const MESES = [
  "janeiro", "fevereiro", "março", "abril", "maio", "junho", 
  "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"
];

export const INDICADOR_OPTIONS = ["+", "-"];
